## roles/vagrant/tasks/main.yml
## Role main file
# vim:ft=ansible:
---
# Initialise distribution-specific variables
#- include_vars: "{{ item }}"
#  with_first_found:
#    - "{{ ansible_distribution }}.yml"
#    - "{{ ansible_os_family }}.yml"
#  tags: vagrant

- include_tasks: roles/vagrant/tasks/Arch Linux.yml
  when: "'Arch' in ansible_distribution"
  tags: vagrant

#- include: CentOS.yml
#  when: "'CentOS' in ansible_distribution"
#  tags: 

...
